//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class bkpTbl_Medication
    {
        public int Medication_Id { get; set; }
        public Nullable<int> CheckUp_Id { get; set; }
        public string Name { get; set; }
        public string Dosage { get; set; }
        public string Frequency { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Created_On { get; set; }
        public string Created_By { get; set; }
        public string Update_On { get; set; }
        public string Updated_By { get; set; }
        public Nullable<int> bp_Id { get; set; }
        public Nullable<int> Dosage_Id { get; set; }
    }
}
