//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Clc_App_CHKEntities : DbContext
    {
        public Clc_App_CHKEntities()
            : base("name=Clc_App_CHKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_W_Address> Table_W_Address { get; set; }
        public virtual DbSet<Table_W_AddressUserMaping> Table_W_AddressUserMaping { get; set; }
        public virtual DbSet<Table_W_Role> Table_W_Role { get; set; }
        public virtual DbSet<Table_W_User> Table_W_User { get; set; }
        public virtual DbSet<Table_W_UserRoleMapping> Table_W_UserRoleMapping { get; set; }
        public virtual DbSet<Tbl_Address> Tbl_Address { get; set; }
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_BP> Tbl_BP { get; set; }
        public virtual DbSet<Tbl_District> Tbl_District { get; set; }
        public virtual DbSet<Tbl_Dosage> Tbl_Dosage { get; set; }
        public virtual DbSet<Tbl_Encounters> Tbl_Encounters { get; set; }
        public virtual DbSet<Tbl_facility> Tbl_facility { get; set; }
        public virtual DbSet<Tbl_Med> Tbl_Med { get; set; }
        public virtual DbSet<Tbl_Medication> Tbl_Medication { get; set; }
        public virtual DbSet<Tbl_Patient> Tbl_Patient { get; set; }
        public virtual DbSet<Tbl_State> Tbl_State { get; set; }
        public virtual DbSet<Tbl_Suggested_Medicine> Tbl_Suggested_Medicine { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
        public virtual DbSet<bkpTbl_BP> bkpTbl_BP { get; set; }
        public virtual DbSet<bkpTbl_Medication> bkpTbl_Medication { get; set; }
        public virtual DbSet<TblBKBP> TblBKBPs { get; set; }
        public virtual DbSet<TblBKPAT> TblBKPATs { get; set; }
        public virtual DbSet<TblBKPMED> TblBKPMEDs { get; set; }
    }
}
