//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_W_Address
    {
        public int Id { get; set; }
        public string Area { get; set; }
        public int PlotNo { get; set; }
        public string Street { get; set; }
        public string District { get; set; }
        public string Description { get; set; }
        public string Latitude { get; set; }
        public string longitude { get; set; }
        public string PhoneNumber { get; set; }
    }
}
