//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Encounters
    {
        public int CheckUp_id { get; set; }
        public string date { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public string next_Appointment_date { get; set; }
        public string name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Created_On { get; set; }
        public string Created_By { get; set; }
        public string Updated_On { get; set; }
        public string Updated_By { get; set; }
        public Nullable<int> bp_Id { get; set; }
        public Nullable<decimal> insertion_Timestamp { get; set; }
        public Nullable<decimal> next_Appointment_Timestamp { get; set; }
    }
}
