//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Dosage
    {
        public int Dosage_Id { get; set; }
        public string Dosage_name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Created_On { get; set; }
        public string Created_By { get; set; }
        public string Updated_On { get; set; }
        public string Updated_By { get; set; }
        public string Med_Name { get; set; }
        public string Dosage_Range { get; set; }
    }
}
