//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_facility
    {
        public int facility_Id { get; set; }
        public string name { get; set; }
        public Nullable<int> address_Id { get; set; }
        public string facility_Type { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<bool> IsAstive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> created_On { get; set; }
        public string created_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public string Update_By { get; set; }
        public Nullable<int> facility_Group_Id { get; set; }
    }
}
