//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_District
    {
        public int district_Id { get; set; }
        public string district_Name { get; set; }
        public string state_name { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public string created_On { get; set; }
        public string created_By { get; set; }
        public string updated_On { get; set; }
        public string updated_By { get; set; }
    }
}
