//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Suggested_Medicine
    {
        public int S_Medicine_Id { get; set; }
        public string S_Medicine_Name { get; set; }
        public string S_Medicine_Dosage { get; set; }
        public Nullable<bool> S_Is_Active { get; set; }
        public Nullable<bool> S_Is_Deleted { get; set; }
        public string S_Created_On { get; set; }
        public string S_Created_By { get; set; }
        public string S_Updated_On { get; set; }
        public string S_Updated_By { get; set; }
    }
}
