//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Address
    {
        public int address_Id { get; set; }
        public string street_Address { get; set; }
        public string village_Or_Colony { get; set; }
        public string district { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string pin { get; set; }
        public string name { get; set; }
        public Nullable<bool> is_Active { get; set; }
        public Nullable<bool> is_Deleted { get; set; }
        public Nullable<System.DateTime> created_On { get; set; }
        public string created_By { get; set; }
        public Nullable<System.DateTime> update_On { get; set; }
        public string update_By { get; set; }
    }
}
