//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBKPAT
    {
        public int patient_Id { get; set; }
        public Nullable<System.DateTime> N_date_Of_Brith { get; set; }
        public string date_Of_Brith { get; set; }
        public Nullable<System.DateTime> N_Recorded_at { get; set; }
        public string recorded_at { get; set; }
        public Nullable<System.DateTime> N_Enrollment_Date { get; set; }
        public string Enrollment_Date { get; set; }
        public Nullable<System.DateTime> N_created_On { get; set; }
        public string created_On { get; set; }
    }
}
